basePath: /
definitions:
  api.SendRequest:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  api.VerifyRequest:
    properties:
      code:
        type: string
      phone:
        type: string
    required:
    - code
    - phone
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для генерации и проверки TOTP-кодов, отправляемых по SMS
  title: TOTP SMS Auth API
  version: "1.0"
paths:
  /send:
    post:
      consumes:
      - application/json
      description: Generates TOTP for given phone and records send time
      parameters:
      - description: Phone
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.SendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Code sent
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "429":
          description: Too many requests
          schema:
            type: string
      summary: Generate and send TOTP code via SMS
  /verify:
    post:
      consumes:
      - application/json
      description: Checks provided TOTP code for validity
      parameters:
      - description: Code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Code valid
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Invalid code
          schema:
            type: string
      summary: Validate TOTP code
swagger: "2.0"
